apiVersion: batch/v1
kind: CronJob
metadata:
  name: spring-report
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit : 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: spring-report
              image: fallendev/spring-jobs:1.0
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure

